package com.rcmapps.smartwallet.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.rcmapps.smartwallet.db.Expense;

import com.rcmapps.smartwallet.db.ExpenseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expenseDaoConfig;

    private final ExpenseDao expenseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        expenseDao = new ExpenseDao(expenseDaoConfig, this);

        registerDao(Expense.class, expenseDao);
    }
    
    public void clear() {
        expenseDaoConfig.getIdentityScope().clear();
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

}
