package com.rcmapps.smartwallet.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.rcmapps.smartwallet.db.Expense;
import com.rcmapps.smartwallet.db.Budget;

import com.rcmapps.smartwallet.db.ExpenseDao;
import com.rcmapps.smartwallet.db.BudgetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig expenseDaoConfig;
    private final DaoConfig budgetDaoConfig;

    private final ExpenseDao expenseDao;
    private final BudgetDao budgetDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        budgetDaoConfig = daoConfigMap.get(BudgetDao.class).clone();
        budgetDaoConfig.initIdentityScope(type);

        expenseDao = new ExpenseDao(expenseDaoConfig, this);
        budgetDao = new BudgetDao(budgetDaoConfig, this);

        registerDao(Expense.class, expenseDao);
        registerDao(Budget.class, budgetDao);
    }
    
    public void clear() {
        expenseDaoConfig.getIdentityScope().clear();
        budgetDaoConfig.getIdentityScope().clear();
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

    public BudgetDao getBudgetDao() {
        return budgetDao;
    }

}
